# Generated by Django 2.0 on 2017-12-26 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre o razon social')),
                ('cedula_identidad', models.CharField(blank=True, max_length=10, null=True, verbose_name='cedula de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'permissions': (('view_funcionario', 'Puede ver la lista de funcionarios'),),
            },
        ),
        migrations.CreateModel(
            name='FuncionarioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario', unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='usuario asignado')),
            ],
            options={
                'permissions': (('can_assign_user', 'Puede asignar un usuario a un funcionario'),),
            },
        ),
    ]
