# Generated by Django 2.0 on 2017-12-27 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionariousuario',
            options={'permissions': (('can_assign_user', 'Puede asignar un usuario a un funcionario'),), 'verbose_name': 'usuario asignado a un funcionario', 'verbose_name_plural': 'usuario asignado a un funcionario'},
        ),
        migrations.AlterField(
            model_name='funcionariousuario',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionariousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario asignado'),
        ),
    ]
