# Generated by Django 2.0 on 2017-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20171227_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='apellidos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nombres',
            field=models.CharField(default='Perez', max_length=200),
            preserve_default=False,
        ),
    ]
