# Generated by Django 2.0 on 2017-12-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20171227_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='apellidos',
            field=models.CharField(default='perez', max_length=200),
            preserve_default=False,
        ),
    ]
