# Generated by Django 2.0 on 2017-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20171227_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
