# Generated by Django 2.0 on 2017-12-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('existencia', models.IntegerField(default=0, editable=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'permissions': (('view_articulo', 'Puede ver la lista de articulos'),),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'permissions': (('view_categoria', 'Puede ver la lista de categorias'),),
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(to='proveedores.proveedor'),
        ),
    ]
