# Generated by Django 2.0 on 2017-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(null=True, to='proveedores.proveedor'),
        ),
    ]
