# Generated by Django 2.0 on 2017-12-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20171226_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.proveedor'),
        ),
    ]
