# Generated by Django 2.0 on 2017-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20171227_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.Proveedor'),
        ),
    ]
