# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_auto_20171227_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(default='abc', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.Proveedor'),
        ),
    ]
