# Generated by Django 2.0 on 2017-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'permissions': (('view_servicio', 'Puede ver la lista de servicios'),),
            },
        ),
    ]
