# Generated by Django 2.0 on 2017-12-26 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aprobado', models.BooleanField(default=False, editable=False)),
                ('borrado', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_presupuesto', 'Puede ver la lista de presupuesto'), ('accept_presupuesto', 'Puede aprobar un presupuesto')),
            },
        ),
        migrations.CreateModel(
            name='PresupuestoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrado', models.BooleanField(default=False, editable=False)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Presupuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio')),
            ],
        ),
    ]
