# Generated by Django 2.0 on 2017-12-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_auto_20171227_0933'),
        ('servicios', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='presupuestoarticulo',
            name='servicio',
        ),
        migrations.AddField(
            model_name='presupuestoarticulo',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_carga',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de carga'),
        ),
        migrations.AddField(
            model_name='presupuestoservicio',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Presupuesto'),
        ),
        migrations.AddField(
            model_name='presupuestoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
    ]
