# Generated by Django 2.0 on 2017-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre o razon social')),
                ('ruc', models.CharField(blank=True, max_length=10, null=True, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('borrado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'permissions': (('view_proveedor', 'Puede ver la lista de proveedores'),),
            },
        ),
    ]
